/**
 * CS1010 Semester 1 AY24/25
 * Practical Exam 0: Sierpinski
 *
 * @file: sierpinski-main.c
 * @author: Ooi Wei Tsang
 */
#include "cs1010.h"

// DO NOT EDIT THIS FILE.

void print_spaces(long n)
{
  for (long i = 0; i < n; i += 1) {
    cs1010_print_string(" ");
  }
}

long power_of_two(long n)
{
  if (n == 0) {
    return 1;
  }
  return 2 * power_of_two(n - 1);
}

// complete this function in the file sierpinski.c
void draw_sierpinski(long row, long level);

int main()
{
  long i = cs1010_read_long();
  long height = power_of_two(i);

  for (long row = 0; row < height; row += 1) {
    draw_sierpinski(i, row);
    cs1010_println_string("");
  }
}
